// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package mock

import (
	"app_module__/internal/app/model/gorm"
	"app_module__/internal/app/model/gorm/model"
)

// Injectors from wire.go:

func BuildModelInjector() (*ModelInjector, func(), error) {
	db, cleanup, err := gorm.InitGormDB()
	if err != nil {
		return nil, nil, err
	}
	messageTypeName__ := &model.MessageTypeName__{
		DB: db,
	}
	modelInjector := &ModelInjector{
		MessageTypeName__Model: messageTypeName__,
	}
	return modelInjector, func() {
		cleanup()
	}, nil
}
