// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pkg/proto/gopackage_name__/types.proto

package gopackage_name__

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _types_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on MessageTypeName__ with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *MessageTypeName__) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MessageTypeName__ValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MessageTypeName__ValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// MessageTypeName__ValidationError is the validation error returned by
// MessageTypeName__.Validate if the designated constraints aren't met.
type MessageTypeName__ValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MessageTypeName__ValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MessageTypeName__ValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MessageTypeName__ValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MessageTypeName__ValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MessageTypeName__ValidationError) ErrorName() string {
	return "MessageTypeName__ValidationError"
}

// Error satisfies the builtin error interface
func (e MessageTypeName__ValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessageTypeName__.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MessageTypeName__ValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MessageTypeName__ValidationError{}

// Validate checks the field values on MessageTypeNamePlural__ with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *MessageTypeNamePlural__) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return MessageTypeNamePlural__ValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MessageTypeNamePlural__ValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// MessageTypeNamePlural__ValidationError is the validation error returned by
// MessageTypeNamePlural__.Validate if the designated constraints aren't met.
type MessageTypeNamePlural__ValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MessageTypeNamePlural__ValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MessageTypeNamePlural__ValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MessageTypeNamePlural__ValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MessageTypeNamePlural__ValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MessageTypeNamePlural__ValidationError) ErrorName() string {
	return "MessageTypeNamePlural__ValidationError"
}

// Error satisfies the builtin error interface
func (e MessageTypeNamePlural__ValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessageTypeNamePlural__.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MessageTypeNamePlural__ValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MessageTypeNamePlural__ValidationError{}
