// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector

import (
	"app_module__/internal/app/model/gorm"
	"app_module__/internal/app/model/gorm/model"
	"app_module__/internal/app/service"
	"app_module__/internal/app/service/v1/gopackage_name__"
	"app_module__/internal/pkg/server/rpc"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, func(), error) {
	db, cleanup, err := gorm.InitGormDB()
	if err != nil {
		return nil, nil, err
	}
	messageTypeName__ := &model.MessageTypeName__{
		DB: db,
	}
	pbName__Service := &gopackage_name__.PbName__Service{
		PbName__Model: messageTypeName__,
	}
	register := &service.Register{
		PbName__ServiceV1: pbName__Service,
	}
	server := &rpc.Server{
		Register: register,
	}
	injector := &Injector{
		Server: server,
	}
	return injector, func() {
		cleanup()
	}, nil
}
