// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package mock

import (
	"GOMA/internal/app/model/gorm"
	"GOMA/internal/app/model/gorm/model"
	"GOMA/internal/app/service/v1/order"
	order2 "GOMA/internal/app/service/v2/order"
)

// Injectors from wire.go:

func BuildMockInjector() (*MockInjector, func(), error) {
	db, cleanup, err := gorm.InitGormDB()
	if err != nil {
		return nil, nil, err
	}
	modelOrder := &model.Order{
		DB: db,
	}
	orderService := &order.OrderService{
		OrderModel: modelOrder,
	}
	orderOrderService := &order2.OrderService{
		OrderModel: modelOrder,
	}
	mockInjector := &MockInjector{
		OrderServiceV1: orderService,
		OrderServiceV2: orderOrderService,
	}
	return mockInjector, func() {
		cleanup()
	}, nil
}
