// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package mock

import (
	"app_module__/internal/app/model/gorm"
	"app_module__/internal/app/model/gorm/model"
	"app_module__/internal/app/service/v1/gopackage_name__"
)

// Injectors from wire.go:

func BuildMockInjector() (*MockInjector, func(), error) {
	db, cleanup, err := gorm.InitGormDB()
	if err != nil {
		return nil, nil, err
	}
	messageTypeName__ := &model.MessageTypeName__{
		DB: db,
	}
	pbName__Service := &gopackage_name__.PbName__Service{
		PbName__Model: messageTypeName__,
	}
	mockInjector := &MockInjector{
		OrderServiceV1: pbName__Service,
	}
	return mockInjector, func() {
		cleanup()
	}, nil
}
